"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleEllipsis, ClipboardCheck, Clock3, FileCheck2, GraduationCap } from "lucide-react";
import { DocumentStatus } from "@/components/platform/documents/DocumentStatus";
import { LawyerRouteGuard } from "./LawyerRouteGuard";
import { PriorityBadge } from "./PriorityBadge";
import { useLawyerCases } from "./useLawyerCases";
import { PlatformShell } from "@/components/platform/PlatformShell";
import { PlanBadge, PlatformCard, ProfileAvatar, ProgressBar } from "@/components/platform/PlatformPrimitives";
import { ProcedureProgress } from "@/components/platform/dashboard/ProcedureProgress";
import { Button } from "@/components/ui/button";
import { getDashboardForIdentity } from "@/lib/platform/demo";
import { LAWYER_TASKS, useLawyerTaskSnapshot, type LawyerTaskStatus } from "./LawyerTasks";

export function LawyerCaseDetail({ caseNumber }: { caseNumber: string }) { return <LawyerRouteGuard><PlatformShell><CaseContent caseNumber={caseNumber} /></PlatformShell></LawyerRouteGuard>; }
function CaseContent({ caseNumber }: { caseNumber: string }) {
  const entries = useLawyerCases();
  const entry = entries.find((item) => item.summary.clientCase.caseNumber === caseNumber)!;
  const item = entry.summary;
  const [feedback, setFeedback] = useState<string>();
  const dashboard = getDashboardForIdentity(item.identity.id)!;
  const sent = item.documents.filter((document) => document.status === "sent_for_review");
  const taskState = useLawyerTaskSnapshot();
  const caseTasks = LAWYER_TASKS.filter((task) => task.caseNumber === caseNumber).sort((a, b) => Number((taskState[a.id] ?? "new") === "done") - Number((taskState[b.id] ?? "new") === "done") || a.dueOrder - b.dueOrder);
  const documentEvents = item.documents.filter((document) => document.status === "sent_for_review" || document.status === "reviewed").map((document) => ({ id: document.definition.id, text: document.status === "reviewed" ? `Документ «${document.definition.title}» проверен` : `Документ «${document.definition.title}» передан на проверку`, date: new Intl.DateTimeFormat("ru-RU", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Moscow" }).format(new Date(document.updatedAt)) }));
  function review(id: string) { entry.markReviewed(id); setFeedback("Документ отмечен как проверенный. Статус доступен клиенту."); }
  return <div className="flex min-w-0 flex-col gap-7 sm:gap-9"><Link href="/app/lawyer/cases" className="inline-flex w-fit items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />К списку дел</Link>
    <header className="flex min-w-0 flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="flex min-w-0 items-start gap-4"><ProfileAvatar initials={item.identity.initials} className="size-12" /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><PlanBadge plan={item.clientCase.plan} /><PriorityBadge priority={item.priority} /></div><h1 className="mt-4 break-words text-3xl font-semibold tracking-[-.045em] sm:text-4xl">{item.identity.displayName}</h1><p className="mt-2 text-sm text-muted-foreground">Дело № {item.clientCase.caseNumber} · открыто {item.clientCase.openedDate}</p></div></div></header>
    {feedback ? <div role="status" className="flex gap-3 rounded-2xl border border-primary/20 bg-primary/8 p-4 text-sm"><CheckCircle2 className="size-5 shrink-0 text-primary" />{feedback}</div> : null}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><PlatformCard className="p-5"><p className="text-sm text-muted-foreground">Статус</p><p className="mt-3 text-xl font-semibold">{item.clientCase.status}</p></PlatformCard><PlatformCard className="p-5"><p className="text-sm text-muted-foreground">Текущий этап</p><p className="mt-3 text-xl font-semibold">{item.clientCase.stage}</p></PlatformCard><PlatformCard className="p-5"><p className="text-sm text-muted-foreground">Общий прогресс</p><p className="mt-3 text-3xl font-semibold">{item.clientCase.progress}%</p><div className="mt-4"><ProgressBar value={item.clientCase.progress} /></div></PlatformCard><PlatformCard className="p-5"><p className="text-sm text-muted-foreground">Назначенный юрист</p><p className="mt-3 text-xl font-semibold">{item.clientCase.assignedLawyer}</p></PlatformCard></section>
    <ProcedureProgress currentStageIndex={dashboard.currentStageIndex} />
    <section className="grid gap-4 lg:grid-cols-3"><StatusCard icon={GraduationCap} title="Практикум" value={`${item.practicum.completedCount} из 12`} progress={item.practicum.progress} detail={item.practicum.currentLessonTitle ? `Текущий урок: ${item.practicum.currentLessonTitle}` : "Обучение завершено"} /><StatusCard icon={ClipboardCheck} title="Анкета" value={`${item.questionnaire.completedCount} из 10`} progress={item.questionnaire.progress} detail={item.questionnaire.isComplete ? "Анкета заполнена" : `Текущий раздел: ${item.questionnaire.currentSectionTitle}`} /><StatusCard icon={FileCheck2} title="Документы" value={`${item.documents.length} документа`} progress={Math.round(item.documents.reduce((sum, document) => sum + document.completeness, 0) / item.documents.length)} detail={item.attentionReason} /></section>
    {caseTasks.length ? <PlatformCard className="min-w-0 overflow-hidden"><div className="flex flex-col gap-3 border-b border-border px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><h2 className="text-xl font-semibold tracking-[-.03em]">Следующие действия</h2><p className="mt-1 text-sm text-muted-foreground">Рабочие задачи по текущему делу</p></div><Button render={<Link href="/app/lawyer/tasks" />} nativeButton={false} variant="outline" className="h-10 w-full rounded-full sm:w-auto">Открыть задачи<ArrowRight data-icon="inline-end" /></Button></div><div className="divide-y divide-border">{caseTasks.slice(0, 3).map((task) => { const status = taskState[task.id] ?? "new"; return <div key={task.id} className="grid min-w-0 gap-3 px-5 py-3.5 sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-center sm:px-6"><div className="min-w-0"><p className="text-sm font-semibold">{task.title}</p><p className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><Clock3 className="size-3.5" />{task.due}</p></div><TaskStatus status={status} /><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.1em] ${task.group === "overdue" || task.group === "urgent" ? "bg-primary/10 text-primary" : "bg-muted text-muted-foreground"}`}>{status === "done" ? "Завершено" : task.group === "overdue" ? "Просрочено" : task.group === "urgent" ? "Срочно" : task.group === "today" ? "Сегодня" : "Неделя"}</span></div>; })}</div></PlatformCard> : null}
    <section className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(19rem,.85fr)]"><PlatformCard className="min-w-0 overflow-hidden"><div className="border-b border-border p-5 sm:p-6"><h2 className="text-2xl font-semibold tracking-[-.04em]">Документы</h2><p className="mt-2 text-sm text-muted-foreground">Статусы синхронизированы с клиентским кабинетом.</p></div><div className="divide-y divide-border">{item.documents.map((document) => <div key={document.definition.id} className="flex min-w-0 flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="min-w-0"><p className="break-words font-semibold">{document.definition.title}</p><div className="mt-2"><DocumentStatus status={document.status} /></div></div>{document.status === "sent_for_review" ? <Button type="button" className="h-auto min-h-10 w-full whitespace-normal rounded-full sm:w-auto" onClick={() => review(document.definition.id)}>Отметить как проверено</Button> : null}</div>)}</div></PlatformCard>
      <div className="flex min-w-0 flex-col gap-5"><PlatformCard className="p-5 sm:p-6"><h2 className="text-2xl font-semibold tracking-[-.04em]">Последняя активность</h2><div className="mt-5 flex flex-col gap-4">{documentEvents.map((event) => <div key={event.id} className="flex gap-3"><FileCheck2 className="mt-0.5 size-4 shrink-0 text-primary" /><div><p className="text-sm font-medium">{event.text}</p><p className="mt-1 text-xs text-muted-foreground">{event.date}</p></div></div>)}{dashboard.activity.slice(0, 3).map((event) => <div key={event.id} className="flex gap-3"><CircleEllipsis className="mt-0.5 size-4 shrink-0 text-primary" /><div><p className="text-sm font-medium">{event.text}</p><p className="mt-1 text-xs text-muted-foreground">{event.dateLabel}</p></div></div>)}</div></PlatformCard><PlatformCard className="p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[.15em] text-primary">Важная заметка</p><p className="mt-3 text-sm leading-6 text-muted-foreground">{importantNote(item.identity.id, sent.length > 0)}</p></PlatformCard></div>
    </section>
  </div>;
}

function StatusCard({ icon: Icon, title, value, progress, detail }: { icon: typeof GraduationCap; title: string; value: string; progress: number; detail: string }) { return <PlatformCard className="min-w-0 p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><span className="grid size-10 place-items-center rounded-xl bg-muted text-primary"><Icon className="size-5" /></span><span className="text-xl font-semibold">{value}</span></div><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-2 min-h-10 text-sm leading-5 text-muted-foreground">{detail}</p><div className="mt-5"><ProgressBar value={progress} /></div></PlatformCard>; }

function TaskStatus({ status }: { status: LawyerTaskStatus }) { return <span className={`w-fit rounded-full px-2.5 py-1 text-xs font-semibold ${status === "done" ? "bg-muted text-muted-foreground" : status === "working" ? "bg-[#718b9a]/12 text-[#536f81]" : "bg-card text-foreground ring-1 ring-border"}`}>{status === "done" ? "Завершено" : status === "working" ? "В работе" : "К выполнению"}</span>; }
function importantNote(identityId: string, hasSentDocuments: boolean) { if (identityId === "dmitry-individual") return hasSentDocuments ? "Завершите проверку переданных документов перед переходом к следующему этапу." : "Перед переходом к следующему этапу необходимо завершить проверку подготовленных документов."; if (identityId === "maria-pro") return "Проверьте полноту сведений об имуществе и ипотеке до завершения анкеты."; return "Контролируйте прогресс Практикума и готовность клиента к переходу к анкете."; }
