import type { ClientDocumentState, DocumentDefinition, DocumentPreviewField, DocumentPreviewSection, DocumentStatus, GeneratedDocument, QuestionnaireAnswers } from "../types";

export const DOCUMENT_DEFINITIONS = [
  { id:"bankruptcy-application", title:"Заявление о признании гражданина банкротом", description:"Демонстрационный черновик основных сведений для подготовки заявления.", requiredFieldIds:["fullName","city","totalDebt","creditorCount","monthlyIncome","hasRealEstate"] },
  { id:"property-inventory", title:"Опись имущества", description:"Сводные сведения о недвижимости, транспорте и другом имуществе.", requiredFieldIds:["fullName","hasRealEstate","hasVehicle","hasValuables"] },
  { id:"creditors-list", title:"Список кредиторов и должников", description:"Агрегированный предварительный список обязательств клиента.", requiredFieldIds:["fullName","creditorCount","totalDebt","hasOverdue"] },
  { id:"income-obligations", title:"Сведения о доходах и обязательствах", description:"Источники дохода и ключевые показатели финансовой нагрузки.", requiredFieldIds:["fullName","incomeSource","monthlyIncome","totalDebt"] },
] as const satisfies readonly DocumentDefinition[];

const INITIAL_UPDATED_AT:Record<string,string>={"alexander-lite":"2026-01-18T09:20:00+03:00","maria-pro":"2026-01-22T12:40:00+03:00","dmitry-individual":"2026-01-24T14:30:00+03:00"};
const sourceMap:Record<string,string>={fullName:"Анкета → Основные сведения",city:"Анкета → Основные сведения",monthlyIncome:"Анкета → Доходы",incomeSource:"Анкета → Доходы",totalDebt:"Анкета → Обязательства",creditorCount:"Анкета → Обязательства",hasRealEstate:"Анкета → Имущество",hasVehicle:"Анкета → Имущество",hasValuables:"Анкета → Имущество",hasMortgage:"Анкета → Недвижимость"};
const missing="Требуются данные анкеты";
function text(answers:QuestionnaireAnswers,id:string){const value=answers[id];if(value===undefined||value==="")return missing;if(typeof value==="boolean")return value?"Да":"Нет";if(typeof value==="number")return new Intl.NumberFormat("ru-RU").format(value);return String(value);}
function rubles(answers:QuestionnaireAnswers,id:string){const value=answers[id];return typeof value==="number"?`${new Intl.NumberFormat("ru-RU").format(value)} ₽`:missing;}
function field(label:string,answers:QuestionnaireAnswers,id:string,currency=false):DocumentPreviewField{return{label,value:currency?rubles(answers,id):text(answers,id),source:sourceMap[id]};}
function sectionsFor(id:string,answers:QuestionnaireAnswers):readonly DocumentPreviewSection[]{
  if(id==="bankruptcy-application")return[{title:"Заявитель",fields:[field("ФИО",answers,"fullName"),field("Город проживания",answers,"city")]},{title:"Краткие сведения",fields:[field("Общая сумма задолженности",answers,"totalDebt",true),field("Количество кредиторов",answers,"creditorCount"),field("Среднемесячный доход",answers,"monthlyIncome",true),field("Наличие имущества",answers,"hasRealEstate"),field("Ипотечное жильё",answers,"hasMortgage")]},{title:"Основание для подготовки документа",fields:[],note:"Документ сформирован на основе сведений, указанных пользователем в анкете iБюро."}];
  if(id==="property-inventory")return[{title:"Недвижимость",fields:[field("Наличие недвижимости",answers,"hasRealEstate"),field("Тип объекта",answers,"realEstateType"),field("Ориентировочная стоимость",answers,"realEstateValue",true),field("Ипотека",answers,"hasMortgage")]},{title:"Транспорт",fields:[field("Наличие транспорта",answers,"hasVehicle"),field("Марка и модель",answers,"vehicleModel"),field("Год выпуска",answers,"vehicleYear"),field("Стоимость",answers,"vehicleValue",true)]},{title:"Иное имущество",fields:[field("Наличие ценного имущества",answers,"hasValuables"),field("Описание",answers,"valuablesNote")]}];
  if(id==="creditors-list")return[{title:"Сводные обязательства",fields:[field("Количество кредиторов",answers,"creditorCount"),field("Общая задолженность",answers,"totalDebt",true),field("Наличие просрочек",answers,"hasOverdue"),field("Исполнительные производства",answers,"hasEnforcement")],note:"Названия кредиторов не указаны в демо-анкете. Детализация будет запрошена на следующем этапе."}];
  return[{title:"Доходы",fields:[field("Основной источник",answers,"incomeSource"),field("Среднемесячный доход",answers,"monthlyIncome",true),field("Официальный доход",answers,"officialIncome"),field("Дополнительные доходы",answers,"additionalIncome")]},{title:"Обязательства",fields:[field("Общая задолженность",answers,"totalDebt",true),field("Количество кредиторов",answers,"creditorCount")]}];
}
function statusFor(identityId:string,documentId:string,completeness:number,sent:boolean,reviewed:boolean):DocumentStatus{if(reviewed)return"reviewed";if(sent)return"sent_for_review";if(identityId==="alexander-lite")return"waiting_data";if(identityId==="dmitry-individual")return documentId==="income-obligations"?"draft":completeness===100?"ready_for_review":"draft";return documentId==="bankruptcy-application"||documentId==="income-obligations"?"draft":"waiting_data";}
export function getDocumentDefinition(id:string){return DOCUMENT_DEFINITIONS.find((document)=>document.id===id);}
export function generateDocuments(identityId:string,answers:QuestionnaireAnswers,state:ClientDocumentState):readonly GeneratedDocument[]{return DOCUMENT_DEFINITIONS.map((definition)=>{const present=definition.requiredFieldIds.filter((id)=>answers[id]!==undefined&&answers[id]!=="").length;const completeness=Math.round(present/definition.requiredFieldIds.length*100);const reviewedAt=state.reviewedAtById?.[definition.id];return{definition,completeness,status:statusFor(identityId,definition.id,completeness,state.sentForReviewIds.includes(definition.id),Boolean(reviewedAt)),updatedAt:reviewedAt??state.regeneratedAtById[definition.id]??INITIAL_UPDATED_AT[identityId]??INITIAL_UPDATED_AT["alexander-lite"],sections:sectionsFor(definition.id,answers),usedSources:[...new Set(definition.requiredFieldIds.map((id)=>sourceMap[id]).filter((value):value is string=>Boolean(value)))]};});}
export function serializeDocument(document:GeneratedDocument){const rows=document.sections.flatMap((section)=>[section.title,...section.fields.map((item)=>`${item.label}: ${item.value}`),...(section.note?[section.note]:[])]);return["ДЕМОНСТРАЦИОННАЯ ВЕРСИЯ",document.definition.title,"",...rows,"","Документ требует проверки специалистом перед использованием."].join("\r\n");}
