export { DEMO_CASES, getCaseForIdentity } from "./cases";
export { DEFAULT_CLIENT_IDENTITY, DEMO_IDENTITIES, LAWYER_IDENTITY, MANAGER_IDENTITY, getDemoIdentity } from "./identities";
export { CLIENT_NAVIGATION, LAWYER_NAVIGATION, MANAGER_NAVIGATION } from "./navigation";
export { MANAGER_CLIENTS, MANAGER_EMPLOYEES, MANAGER_ACTIVITY, getManagerClient, getManagerEmployee, getManagerCase } from "./manager";
export { DEMO_TASKS, getTasksForEmployee } from "./tasks";
export type { DemoTask, DemoTaskGroup, DemoTaskStatus } from "./tasks";
export { CLIENT_DASHBOARDS, PROCEDURE_STAGES, getDashboardForIdentity } from "./dashboard";
export { CLIENT_PRACTICUM_STATES, PRACTICUM_LESSONS, PRACTICUM_MODULES, getLessonModule, getPracticumLesson, getPracticumProgress, getPracticumState } from "./practicum";
export { CLIENT_QUESTIONNAIRE_SEEDS, QUESTIONNAIRE_SECTIONS, getQuestionnaireProgress, getQuestionnaireSeed, getQuestionnaireSummary, isQuestionnaireFieldVisible } from "./questionnaire";
export { DOCUMENT_DEFINITIONS, generateDocuments, getDocumentDefinition, getSeededDocumentReadiness, serializeDocument } from "./documents";
export { deriveLawyerCase, getPriorityLabel } from "./lawyer";
