import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

const profilePageSource = await readFile(resolve("app/portal/profile/page.tsx"), "utf8");
const editorSource = await readFile(resolve("components/platform/account/ProfileAccountEditor.tsx"), "utf8");
const profileNameSource = await readFile(resolve("lib/platform/profile-display-name.ts"), "utf8");
const accountOperationsSource = await readFile(resolve("server/account/operations.ts"), "utf8");
const avatarSource = await readFile(resolve("server/account/avatar.ts"), "utf8");
const avatarRouteSource = await readFile(resolve("app/api/platform/account/avatar/route.ts"), "utf8");
const profileRouteSource = await readFile(resolve("app/api/platform/account/profile/route.ts"), "utf8");

assert.match(profilePageSource, /getCurrentAccountProfile\(sessionProvider\)/);
assert.match(profilePageSource, /getCurrentAccountAvatarUrl\(sessionProvider\)/);
assert.match(profilePageSource, /listAccessibleClientCases\(sessionProvider\)/);
assert.match(profilePageSource, /from "@\/lib\/platform\/profile-display-name"/);
assert.match(profilePageSource, /formatProfileDisplayName\(storedDisplayName\)/);
assert.match(profilePageSource, /<ProfileAvatarEditor avatarUrl=\{avatarUrl\} \/>/);
assert.match(profilePageSource, /<ProfileDisplayNameEditor displayName=\{storedDisplayName\} \/>/);
assert.match(profilePageSource, /<ProfileContactEditor field="email" value=\{profile\.email\} \/>/);
assert.match(profilePageSource, /<ProfileContactEditor field="phone" value=\{profile\.phone\} \/>/);
assert.match(profilePageSource, /Для связи и уведомлений/);
assert.match(profilePageSource, /<IBuroClientShellV2[\s\S]*caseId=\{selectedClientCase\.id\}[\s\S]*displayName=\{displayName\}[\s\S]*cases=\{caseOptions\}/);
assert.match(profilePageSource, /<PortalFrame sectionLabel="Профиль" showStaffTasks=\{isStaff\}>/);
assert.doesNotMatch(profilePageSource, /ClientPlanVisualStyles|<ClientCaseFrame/);
assert.match(profilePageSource, /grid min-w-0 gap-5/);
assert.match(profilePageSource, /Контактные данные/);
assert.match(profilePageSource, /min-h-11/);
assert.doesNotMatch(profilePageSource, /localStorage|lib\/platform\/demo|DEMO_/i);

assert.match(editorSource, /fetch\("\/api\/platform\/account\/avatar"/);
assert.match(editorSource, /fetch\("\/api\/platform\/account\/profile"/);
assert.match(editorSource, /image\/jpeg", "image\/png", "image\/webp/);
assert.match(editorSource, /5 \* 1024 \* 1024/);
assert.match(editorSource, /hover:opacity-100/);
assert.match(editorSource, /focus-visible:opacity-100/);
assert.match(editorSource, /sm:flex/);
assert.match(editorSource, /sm:hidden/);
assert.match(editorSource, /aria-label=\{avatarUrl \? "Изменить фотографию профиля" : "Добавить фотографию профиля"\}/);
assert.match(editorSource, /aria-label="Изменить ФИО"/);
assert.match(editorSource, /title="Изменить ФИО"/);
assert.match(editorSource, /export function ProfileContactEditor/);
assert.match(editorSource, /field: "email" \| "phone"/);
assert.match(editorSource, /body: JSON\.stringify\(\{ \[field\]: normalized \}\)/);
assert.match(editorSource, /Контактный email для связи и уведомлений\. Адрес входа не изменяется\./);
assert.match(editorSource, /Укажите корректный email/);
assert.match(editorSource, /Укажите корректный номер телефона/);
assert.match(editorSource, /from "@\/lib\/platform\/profile-display-name"/);
assert.match(editorSource, /formatProfileDisplayName/);
assert.match(editorSource, /formatProfileNameForStorage/);
assert.match(editorSource, /Фамилия Имя Отчество/);
assert.match(editorSource, /aria-busy=\{pending\}/);
assert.doesNotMatch(editorSource, />\s*Изменить имя\s*</);
assert.doesNotMatch(editorSource, /localStorage|lib\/platform\/demo|DEMO_/i);

assert.match(profileNameSource, /\[parts\[1\], parts\[0\], parts\[2\]\]/);
assert.match(profileNameSource, /export function formatProfileDisplayName/);
assert.match(profileNameSource, /export function formatProfileNameForStorage/);
assert.doesNotMatch(profileNameSource, /"use client"/);

assert.match(accountOperationsSource, /requireServerActor\(sessionProvider\)/);
assert.match(accountOperationsSource, /where: \{ id: actor\.userId \}/);
assert.match(accountOperationsSource, /export async function updateCurrentAccountContacts/);
assert.match(accountOperationsSource, /ACCOUNT_PROFILE_INVALID_EMAIL/);
assert.match(accountOperationsSource, /ACCOUNT_PROFILE_INVALID_PHONE/);
assert.match(accountOperationsSource, /ACCOUNT_PROFILE_EMAIL_CONFLICT/);
assert.match(accountOperationsSource, /\^\\\+\?\\d\{7,15\}\$/);
assert.match(avatarSource, /requireServerActor\(sessionProvider\)/);
assert.match(avatarSource, /avatarObjectKeyForUser\(actor\.userId\)/);
assert.match(avatarSource, /allowOverwrite: true/);
assert.doesNotMatch(avatarSource, /avatarObjectKeyForUser\(session\.user\.id\)/);
assert.match(profileRouteSource, /readBoundedJsonBody/);
assert.match(profileRouteSource, /privateJsonResponse/);
assert.match(profileRouteSource, /updateCurrentAccountContacts/);
assert.match(profileRouteSource, /ACCOUNT_PROFILE_EMAIL_CONFLICT/);
assert.match(avatarRouteSource, /createCurrentAccountAvatarDownload\(sessionProvider\)/);
assert.match(avatarRouteSource, /readBinaryBodyWithByteLimit/);
assert.match(avatarRouteSource, /privateResponse/);
assert.match(avatarRouteSource, /MAX_AVATAR_SIZE_BYTES = 5 \* 1024 \* 1024/);

console.log("PROFILE_PRESENTATION_CONTRACT_PASS");
