Foreground true
User clamav
TCPSocket 3310
TCPAddr 127.0.0.1
DatabaseDirectory /var/lib/clamav
LocalSocket /run/clamav/clamd.ctl
PidFile /run/clamav/clamd.pid
ReadTimeout 50
CommandReadTimeout 5
SendBufTimeout 50
MaxConnectionQueueLength 8
MaxThreads 4
MaxQueue 8
MaxFileSize 50M
MaxScanSize 50M
StreamMaxLength 50M
LogFile /dev/stdout
LogTime true
LogClean false
LogVerbose false
ExtendedDetectionInfo false
