Foreground true
DatabaseOwner clamav
DatabaseDirectory /var/lib/clamav
DatabaseMirror database.clamav.net
Checks 12
ConnectTimeout 10
ReceiveTimeout 30
NotifyClamd /etc/clamav/clamd.conf
UpdateLogFile /dev/stdout
LogTime true
LogVerbose false
