import type { QuestionnaireAnswer, QuestionnaireAnswers, QuestionnaireField } from "@/lib/platform/types";
import { cn } from "@/lib/utils";

const controlClass = "h-12 min-w-0 max-w-full w-full rounded-xl border border-input bg-background px-3 text-base text-foreground outline-none transition placeholder:text-muted-foreground/65 focus:border-primary focus:ring-3 focus:ring-primary/15 sm:px-4 sm:text-sm";

export function QuestionnaireFieldControl({ field, answers, error, onChange }: { field: QuestionnaireField; answers: QuestionnaireAnswers; error?: string; onChange: (value: QuestionnaireAnswer) => void }) {
  const value = answers[field.id] ?? "";
  const errorId = `${field.id}-error`;
  const describedBy = error ? errorId : field.hint ? `${field.id}-hint` : undefined;

  if (field.type === "yes-no" || field.type === "radio") return <fieldset className="min-w-0" aria-describedby={describedBy}><legend className="max-w-full text-sm font-semibold leading-5">{field.label}{field.required ? <span className="text-primary"> *</span> : null}</legend><div className="mt-3 flex min-w-0 flex-wrap gap-2">{field.options?.map((option) => { const optionValue = field.type === "yes-no" ? option === "Да" : option; const checked = value === optionValue; return <label key={option} className={cn("min-w-20 cursor-pointer rounded-full border px-4 py-2.5 text-center text-sm font-medium transition focus-within:ring-3 focus-within:ring-primary/20", checked ? "border-primary bg-primary text-primary-foreground" : "border-border bg-background hover:border-primary/40")}><input className="sr-only" type="radio" name={field.id} value={option} checked={checked} onChange={() => onChange(optionValue)} />{option}</label>; })}</div>{error ? <p id={errorId} className="mt-2 break-words text-sm text-destructive">{error}</p> : null}</fieldset>;

  const common = { id: field.id, "aria-invalid": Boolean(error), "aria-describedby": describedBy, className: cn(controlClass, error && "border-destructive focus:border-destructive focus:ring-destructive/15") };
  return <div className="flex min-w-0 flex-col gap-2"><label htmlFor={field.id} className="max-w-full break-words text-sm font-semibold leading-5">{field.label}{field.required ? <span className="text-primary"> *</span> : null}</label>{field.type === "select" ? <select {...common} value={String(value)} onChange={(event) => onChange(event.target.value)}><option value="">Выберите вариант</option>{field.options?.map((option) => <option key={option}>{option}</option>)}</select> : field.type === "textarea" ? <textarea {...common} className={cn(common.className, "min-h-28 resize-y py-3")} value={String(value)} placeholder={field.placeholder} onChange={(event) => onChange(event.target.value)} /> : <input {...common} type={field.type === "date" ? "date" : field.type === "number" || field.type === "currency" ? "number" : "text"} inputMode={field.type === "currency" || field.type === "number" ? "numeric" : undefined} min={field.type === "currency" || field.type === "number" ? 0 : undefined} value={String(value)} placeholder={field.placeholder} onChange={(event) => onChange(field.type === "currency" || field.type === "number" ? (event.target.value === "" ? "" : Number(event.target.value)) : event.target.value)} />}{field.hint ? <p id={`${field.id}-hint`} className="break-words text-xs text-muted-foreground">{field.hint}</p> : null}{error ? <p id={errorId} className="break-words text-sm text-destructive">{error}</p> : null}</div>;
}
