import { Check, Circle } from "lucide-react";
import { ProgressBar } from "@/components/platform/PlatformPrimitives";
import { QUESTIONNAIRE_SECTIONS } from "@/lib/platform/demo";
import { cn } from "@/lib/utils";

export function QuestionnaireSectionNav({currentId,completedCount,progress,isCompleted,onSelect}:{currentId:string;completedCount:number;progress:number;isCompleted:(id:string)=>boolean;onSelect:(id:string)=>void}) {
  const current=QUESTIONNAIRE_SECTIONS.find((section)=>section.id===currentId) ?? QUESTIONNAIRE_SECTIONS[0];
  return <><section className="min-w-0 rounded-[1.15rem] border border-border bg-card p-4 text-card-foreground shadow-[0_10px_30px_rgba(0,0,0,.04)] lg:hidden" aria-label="Прогресс анкеты"><div className="flex items-center justify-between gap-4"><div className="min-w-0"><p className="text-xs text-muted-foreground">Раздел {current.number} из 10</p><p className="mt-1 truncate text-sm font-semibold">{current.title}</p></div><p className="shrink-0 text-xl font-semibold tracking-[-.04em]">{progress}%</p></div><div className="mt-3"><ProgressBar value={progress}/></div><label htmlFor="questionnaire-mobile-section" className="mt-4 block text-xs font-medium text-muted-foreground">Перейти к разделу</label><select id="questionnaire-mobile-section" value={currentId} onChange={(event)=>onSelect(event.target.value)} className="mt-2 h-11 min-w-0 w-full rounded-xl border border-input bg-background px-3 text-sm text-foreground outline-none focus:border-primary focus:ring-3 focus:ring-primary/15">{QUESTIONNAIRE_SECTIONS.map((section)=><option key={section.id} value={section.id}>{section.number}. {section.title}{isCompleted(section.id)?" — заполнено":""}</option>)}</select><p className="mt-2 text-xs text-muted-foreground">{completedCount} из 10 разделов заполнено</p></section><aside className="hidden rounded-[1.4rem] border border-border bg-card p-4 text-card-foreground shadow-[0_14px_40px_rgba(0,0,0,.04)] lg:sticky lg:top-28 lg:block lg:self-start">
    <div className="border-b border-border px-2 pb-5"><div className="flex items-end justify-between"><div><p className="text-sm font-medium">Анкета заполнена</p><p className="mt-1 text-3xl font-semibold tracking-[-.05em]">{progress}%</p></div><p className="text-xs text-muted-foreground">{completedCount} из 10</p></div><div className="mt-4"><ProgressBar value={progress}/></div></div>
    <nav aria-label="Разделы анкеты" className="mt-3 flex flex-col gap-2">{QUESTIONNAIRE_SECTIONS.map((section)=>{const active=section.id===currentId;const done=isCompleted(section.id);return <button key={section.id} type="button" onClick={()=>onSelect(section.id)} aria-current={active?"step":undefined} className={cn("flex min-w-0 items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-primary/25",active&&"bg-muted text-foreground",!active&&"text-muted-foreground hover:bg-muted/60 hover:text-foreground")}><span className={cn("relative grid size-7 shrink-0 place-items-center rounded-full border text-[11px] font-semibold",done&&"border-primary bg-primary text-primary-foreground",active&&!done&&"platform-step-current border-primary text-primary")}>{done?<Check className="size-3.5"/>:section.number}</span><span className="truncate">{section.title}</span>{!done&&!active?<Circle className="ml-auto size-2 fill-current opacity-25"/>:null}</button>})}</nav>
  </aside></>;
}
